image: docker:latest

services:
    - docker:dind

stages:
    - test_client

before_script:
    - apk update
    - apk upgrade
    - apk --no-cache add --update git bash nss-tools openssl make py-pip
    - pip install docker-compose
    - git submodule update --init --recursive

test_client:
    stage: test_client
        script:
        - tests/test_client.sh
