version: "3.5"

services:
    reclaim-ui:
        image: reclaimid/ui
        container_name: reclaim-ui
        networks:
            reclaim-net:
                ipv4_address: 10.1.1.2
        environment:
            - VIRTUAL_HOST=ui.reclaim.local

    reclaim-runtime:
        image: registry.gitlab.com/reclaimid/runtime:latest
        container_name: reclaim-runtime
        environment:
            - RECLAIMUI_URL=https://ui.reclaim.local/#/identities
            - RECLAIMAPI_BASE=https://api.reclaim.local
            - VIRTUAL_HOST=api.reclaim.local
            - VIRTUAL_PORT=7776
            - WEBSERVER_IP=10.1.1.4 # should be the same as static assignment for service reclaim-ui
            - JWT_SECRET=${JWT_SECRET}
            - PSW_SECRET=${PSW_SECRET}
        stdin_open: true
        tty: true
        networks:
            reclaim-net:
                ipv4_address: 10.1.1.3
        volumes:
            - reclaim-reclaim:/etc/reclaim
            - reclaim-gnunet:/root/.local/share/gnunet
        ports:
            - "7777:7777"
            - "7776:7776"
            - "2086:2086"

    # proxy companion to serve HTTP(S) requests
    nginx-proxy:
        image: jwilder/nginx-proxy:latest
        container_name: nginx-proxy
        environment:
            - ENABLE_IPV6=true
        networks:
            reclaim-net:
                ipv4_address: 10.1.1.4
        volumes:
            - reclaim-reclaim:/etc/nginx/certs:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - "80:80"
            - "443:443"

volumes:
    reclaim-reclaim:
        name: reclaim-reclaim
    reclaim-gnunet:
        name: reclaim-gnunet
    reclaim-cacert:
        name: reclaim-cacert

networks:
    reclaim-net:
        name: reclaim-network
        driver: bridge
        ipam:
            config:
                - subnet: 10.1.1.0/29

